version: '3.8'

services:
  build-linux:
    build:
      context: .
      target: build-linux
    volumes:
      - ./dist:/app/dist
    environment:
      - CSC_IDENTITY_AUTO_DISCOVERY=false
    
  build-app:
    build:
      context: .
      target: final
    volumes:
      - ./dist-output:/output
    depends_on:
      - build-linux

# For Windows builds (current platform)
  build-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    volumes:
      - ./dist:/app/dist
    environment:
      - CSC_IDENTITY_AUTO_DISCOVERY=false